kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: DEV1
    app.openshift.io/vcs-uri: >-
        https://bcagitlab.intra.bca.co.id/MDZ-TCP/mybcabisnis-web/framework/mage.git
    openshift.io/generated-by: OpenShiftNewBuild
  name: mage
  labels:
    build: mage
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'mage:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
      buildArgs:
        - name: buildEnv
          value: dev
  postCommit: {}
  source:
    type: Git
    git:
      uri: >-
        https://bcagitlab.intra.bca.co.id/MDZ-TCP/mybcabisnis-web/framework/mage.git
      ref: DEV1
    contextDir: packages/wiki
    sourceSecret:
      name: mbb-webserver-git
    triggers:
      - type: Generic
        generic:
          secretReference:
            name: mbb-webserver-generic-webhook-secret
      - type: GitLab
        gitlab:
          secretReference:
            name: mbb-webserver-gitlab-webhook-secret
      - type: ConfigChange
    runPolicy: Serial
