import { Config } from "effect"

function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

function falsy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "false" || value === "0"
}

function number(key: string) {
  const value = process.env[key]
  if (!value) return undefined
  const parsed = Number(value)
  return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined
}

const MAGE_EXPERIMENTAL = truthy("MAGE_EXPERIMENTAL")
const MAGE_DISABLE_CLAUDE_CODE = truthy("MAGE_DISABLE_CLAUDE_CODE")
const MAGE_DISABLE_CLAUDE_CODE_SKILLS =
  MAGE_DISABLE_CLAUDE_CODE || truthy("MAGE_DISABLE_CLAUDE_CODE_SKILLS")
const copy = process.env["MAGE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"]

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  MAGE_AUTO_SHARE: truthy("MAGE_AUTO_SHARE"),
  MAGE_AUTO_HEAP_SNAPSHOT: truthy("MAGE_AUTO_HEAP_SNAPSHOT"),
  MAGE_GIT_BASH_PATH: process.env["MAGE_GIT_BASH_PATH"],
  MAGE_CONFIG: process.env["MAGE_CONFIG"],
  MAGE_CONFIG_CONTENT: process.env["MAGE_CONFIG_CONTENT"],
  MAGE_DISABLE_AUTOUPDATE: truthy("MAGE_DISABLE_AUTOUPDATE"),
  MAGE_ALWAYS_NOTIFY_UPDATE: truthy("MAGE_ALWAYS_NOTIFY_UPDATE"),
  MAGE_DISABLE_PRUNE: truthy("MAGE_DISABLE_PRUNE"),
  MAGE_DISABLE_TERMINAL_TITLE: truthy("MAGE_DISABLE_TERMINAL_TITLE"),
  MAGE_SHOW_TTFD: truthy("MAGE_SHOW_TTFD"),
  MAGE_PERMISSION: process.env["MAGE_PERMISSION"],
  MAGE_DISABLE_DEFAULT_PLUGINS: truthy("MAGE_DISABLE_DEFAULT_PLUGINS"),
  MAGE_DISABLE_LSP_DOWNLOAD: truthy("MAGE_DISABLE_LSP_DOWNLOAD"),
  MAGE_ENABLE_EXPERIMENTAL_MODELS: truthy("MAGE_ENABLE_EXPERIMENTAL_MODELS"),
  MAGE_DISABLE_AUTOCOMPACT: truthy("MAGE_DISABLE_AUTOCOMPACT"),
  MAGE_DISABLE_MODELS_FETCH: truthy("MAGE_DISABLE_MODELS_FETCH"),
  MAGE_DISABLE_MOUSE: truthy("MAGE_DISABLE_MOUSE"),
  MAGE_DISABLE_CLAUDE_CODE,
  MAGE_DISABLE_CLAUDE_CODE_PROMPT: MAGE_DISABLE_CLAUDE_CODE || truthy("MAGE_DISABLE_CLAUDE_CODE_PROMPT"),
  MAGE_DISABLE_CLAUDE_CODE_SKILLS,
  MAGE_DISABLE_EXTERNAL_SKILLS: MAGE_DISABLE_CLAUDE_CODE_SKILLS || truthy("MAGE_DISABLE_EXTERNAL_SKILLS"),
  MAGE_FAKE_VCS: process.env["MAGE_FAKE_VCS"],
  MAGE_SERVER_PASSWORD: process.env["MAGE_SERVER_PASSWORD"],
  MAGE_SERVER_USERNAME: process.env["MAGE_SERVER_USERNAME"],
  MAGE_ENABLE_QUESTION_TOOL: truthy("MAGE_ENABLE_QUESTION_TOOL"),

  // Experimental
  MAGE_EXPERIMENTAL,
  MAGE_EXPERIMENTAL_FILEWATCHER: Config.boolean("MAGE_EXPERIMENTAL_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  MAGE_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("MAGE_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  MAGE_EXPERIMENTAL_ICON_DISCOVERY: MAGE_EXPERIMENTAL || truthy("MAGE_EXPERIMENTAL_ICON_DISCOVERY"),
  MAGE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("MAGE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  MAGE_ENABLE_EXA: truthy("MAGE_ENABLE_EXA") || MAGE_EXPERIMENTAL || truthy("MAGE_EXPERIMENTAL_EXA"),
  MAGE_SUBAGENT: number("MAGE_SUBAGENT") ?? 2,
  MAGE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS: number("MAGE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS"),
  MAGE_EXPERIMENTAL_OUTPUT_TOKEN_MAX: number("MAGE_EXPERIMENTAL_OUTPUT_TOKEN_MAX"),
  MAGE_EXPERIMENTAL_OXFMT: MAGE_EXPERIMENTAL || truthy("MAGE_EXPERIMENTAL_OXFMT"),
  MAGE_EXPERIMENTAL_LSP_TY: truthy("MAGE_EXPERIMENTAL_LSP_TY"),
  MAGE_EXPERIMENTAL_LSP_TOOL: MAGE_EXPERIMENTAL || truthy("MAGE_EXPERIMENTAL_LSP_TOOL"),
  MAGE_EXPERIMENTAL_PLAN_MODE: MAGE_EXPERIMENTAL || truthy("MAGE_EXPERIMENTAL_PLAN_MODE"),
  MAGE_EXPERIMENTAL_MARKDOWN: !falsy("MAGE_EXPERIMENTAL_MARKDOWN"),
  MAGE_MODELS_URL: process.env["MAGE_MODELS_URL"],
  MAGE_MODELS_PATH: process.env["MAGE_MODELS_PATH"],
  MAGE_DISABLE_EMBEDDED_WEB_UI: truthy("MAGE_DISABLE_EMBEDDED_WEB_UI"),
  MAGE_DB: process.env["MAGE_DB"],
  MAGE_DISABLE_CHANNEL_DB: truthy("MAGE_DISABLE_CHANNEL_DB"),
  MAGE_SKIP_MIGRATIONS: truthy("MAGE_SKIP_MIGRATIONS"),
  MAGE_STRICT_CONFIG_DEPS: truthy("MAGE_STRICT_CONFIG_DEPS"),

  MAGE_WORKSPACE_ID: process.env["MAGE_WORKSPACE_ID"],
  MAGE_EXPERIMENTAL_HTTPAPI: truthy("MAGE_EXPERIMENTAL_HTTPAPI"),
  MAGE_EXPERIMENTAL_WORKSPACES: MAGE_EXPERIMENTAL || truthy("MAGE_EXPERIMENTAL_WORKSPACES"),

  // Evaluated at access time (not module load) because tests, the CLI, and
  // external tooling set these env vars at runtime.
  get MAGE_DISABLE_PROJECT_CONFIG() {
    return truthy("MAGE_DISABLE_PROJECT_CONFIG")
  },
  get MAGE_TUI_CONFIG() {
    return process.env["MAGE_TUI_CONFIG"]
  },
  get MAGE_CONFIG_DIR() {
    return process.env["MAGE_CONFIG_DIR"]
  },
  get MAGE_PURE() {
    return truthy("MAGE_PURE")
  },
  get MAGE_PLUGIN_META_FILE() {
    return process.env["MAGE_PLUGIN_META_FILE"]
  },
  get MAGE_CLIENT() {
    return process.env["MAGE_CLIENT"] ?? "cli"
  },
}
